version: "3.5"

networks:
    application:
        name: application

volumes:
    mysql-data:
        name: mysql-data
        driver: local
    storage-ocr:
        name: storage-ocr
        driver: local

services:
    web:
        image: bref/fpm-dev-gateway
        container_name: web
        ports:
            - "8080:80"
        volumes:
            - .:/var/task
        links:
            - php
        environment:
            HANDLER: public/index.php
            DOCUMENT_ROOT: public
        networks:
            - application
    php:
        image: bref/php-81-fpm-dev
        container_name: php
        volumes:
            - .:/var/task:ro
        networks:
            - application
    localstack:
        image: localstack/localstack
        container_name: localstack
        ports:
            - "127.0.0.1:4510-4559:4510-4559"
            - "127.0.0.1:4566:4566"
        environment:
            - SERVICES=dynamodb,s3
            - DEBUG=1
            - DATA_DIR=/tmp/localstack/data
            - DOCKER_HOST=unix:///var/run/docker.sock
            - HOST_TMP_FOLDER=${TMPDIR}
        volumes:
            - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
            - "/var/run/docker.sock:/var/run/docker.sock"
        networks:
            - application
    mysql:
        image: mysql:5.7
        container_name: mysql
        # restart: always
        ports:
          - "3306:3306"
        networks:
            - application
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - mysql-data:/var/lib/mysql
