version: "3.5"

networks:
    application:
        name: application

services:
    web:
        image: bref/fpm-dev-gateway
        container_name: web
        ports:
            - "8080:80"
        volumes:
            - .:/var/task
        links:
            - php
        environment:
            HANDLER: public/index.php
            DOCUMENT_ROOT: public
        networks:
            - application
    php:
        image: bref/php-81-fpm-dev
        container_name: php
        volumes:
            - .:/var/task:ro
        networks:
            - application
    localstack:
        image: localstack/localstack
        container_name: localstack
        ports:
            - "127.0.0.1:4510-4559:4510-4559"
            - "127.0.0.1:4566:4566"
        environment:
            - SERVICES=dynamodb,s3
            - DEBUG=1
            - DATA_DIR=/tmp/localstack/data
            - DOCKER_HOST=unix:///var/run/docker.sock
            - HOST_TMP_FOLDER=${TMPDIR}
        volumes:
            - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
            - "/var/run/docker.sock:/var/run/docker.sock"
        networks:
            - application
